<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BusinessLogicLayer\BusinessLogicLayer.csproj" />
      <ProjectReference Include="..\DataAccessLayer\DataAccessLayer.csproj" />
      <ProjectReference Include="..\DTO\DTO.csproj" />
      <ProjectReference Include="..\MVC App\MVC App.csproj" />
    </ItemGroup>

</Project>
